config:
  # Force 64 parallel jobs, otherwise we are limited to 16
  build_jobs: 64
  # FIXME Work around concretizer bugs:
  # https://github.com/spack/spack/issues/26585
  # https://github.com/spack/spack/issues/26598
  concretizer: original
