modules:
  prefix_inspections:
    # LD_LIBRARY_PATH is not set by default anymore (https://github.com/spack/spack/pull/28354)
    # LIBRARY_PATH and *_INCLUDE_PATH are not set by default anymore (https://github.com/spack/spack/pull/21699)
    include:
      - C_INCLUDE_PATH
      - CPLUS_INCLUDE_PATH
    # LD_RUN_PATH automatically sets the rpath if users do not overwrite it (https://github.com/spack/spack/pull/11071)
    lib:
      - LD_LIBRARY_PATH
      - LIBRARY_PATH
      - LD_RUN_PATH
    lib64:
      - LD_LIBRARY_PATH
      - LIBRARY_PATH
      - LD_RUN_PATH
  default:
    enable:
      # We are only interested in tcl modules
      - tcl
    tcl:
      projections:
        # We want to be able to do "module load $pkg"
        all: "{name}/{version}"
      # Create a module for the compiler we build using the system compiler
      whitelist: ["gcc"]
      # Do not generate modules for anything built with the system compiler
      # Keep in sync with install script and packages.yaml
      blacklist: ["%gcc@8.5.0"]
      # Hide modules for implicit packages, that is, dependencies
      # FIXME requires modules >= 4.7 (https://github.com/spack/spack/issues/40940)
      hide_implicits: false
      all:
        # Only load direct dependencies
        autoload: "run"
        # FIXME Causes conflicts because GCC depends on conflicting packages
        #conflict: ['{name}']
