modules:
  prefix_inspections:
    # LD_LIBRARY_PATH is not set by default anymore (https://github.com/spack/spack/pull/28354)
    # LIBRARY_PATH and *_INCLUDE_PATH are not set by default anymore (https://github.com/spack/spack/pull/21699)
    include:
      - C_INCLUDE_PATH
      - CPLUS_INCLUDE_PATH
    # LD_RUN_PATH automatically sets the rpath if users do not overwrite it (https://github.com/spack/spack/pull/11071)
    lib:
      - LIBRARY_PATH
      - LD_RUN_PATH
    lib64:
      - LIBRARY_PATH
      - LD_RUN_PATH
  default:
    enable:
      # We are only interested in tcl modules
      - tcl
    tcl:
      projections:
        # We want to be able to do "module load $pkg"
        all: "{name}/{version}"
      # Create a module for the compiler we build using the system compiler
      include: ["gcc"]
      # Do not generate modules for anything else built with the system compiler
      # Keep in sync with bootstrap script
      exclude: ["%gcc@8", "%gcc@11"]
      # Hide modules for dependencies
      hide_implicits: true
      all:
        # Only load run dependencies
        autoload: "run"
        # FIXME Causes conflicts because GCC depends on conflicting packages
        #conflict: ['{name}']
        # Do not set compiler variables because llvm is required by some packages
        # FIXME https://github.com/spack/spack/issues/42095
        filter:
          exclude_env_vars: ["CC", "CXX", "FC", "F77"]
