packages:
  adios:
    require: "+hdf5"
  adios2:
    require: "+hdf5"
  binutils:
    # LLVM depends on binutils with these variants
    require: "+gold+headers+ld+plugins"
  boost:
    # Valgrind depends on Boost with these variants
    require: "+atomic+chrono+exception+system+thread"
  cairo:
    # FIXME +svg cannot be concretized at the moment
    require: "+fc+ft+gobject+pdf+png+X"
  curl:
    require: "+libidn2+nghttp2"
  doxygen:
    require: "+graphviz"
  gdb:
    # FIXME +debuginfod causes elfutils to fail building
    require: "~debuginfod~python"
  gnuplot:
    require: "+X"
  hdf5:
    require: "+hl+szip+threadsafe"
  julia:
    # FIXME llvm@14.0.6 required by jula@1.9 currently does not compile
    version: [1.8.5]
  libfabric:
    require: "fabrics=sockets,tcp,udp,verbs,rxd,rxm"
  libfuse:
    # FIXME Check whether this needs to be the same version as the system FUSE
    require: "~utils"
  libssh2:
    require: "crypto=mbedtls"
  mbedtls:
    require: "libs=shared,static"
  mpi:
    require: "mpich"
  mpich:
    require: "device=ch4 netmod=ofi"
  octave:
    require: "+arpack+fftw+fontconfig+freetype+gl2ps+gnuplot+hdf5+llvm+opengl+qrupdate+qscintilla+qt+readline+suitesparse"
  pango:
    require: "+X"
  pcre:
    require: "+jit"
  py-numpy:
    # FIXME We currently end up with two versions of py-numpy (and many dependents)
    version: [1.23.5]
  py-setuptools:
    # FIXME We currently end up with two versions of py-setuptools (and many dependents)
    version: [63.0.0]
  py-torch:
    require: "~mkldnn"
  qt:
    require: "+opengl"
  qt-base:
    require: "+opengl"
  vim:
    require: "features=huge +python"
  zstd:
    require: "+programs"
  all:
    # FIXME We cannot use requirements here (https://github.com/spack/spack/issues/34341)
    # Keep in sync with install script
    compiler: [gcc@12.3.0]
    # Make sure to build for a generic architecture
    target: [x86_64_v3]
    # Warning: Adding global variants resets per-package variants (https://github.com/spack/spack/pull/10466)
