packages:
  adios:
    variants: +hdf5
  adios2:
    variants: +hdf5
  cairo:
    # FIXME +svg leads to "maximum recursion depth exceeded" (original concretizer)
    variants: +fc+ft+gobject+pdf+png+X
  doxygen:
    variants: +graphviz
  gdb:
    variants: ~python
  gnuplot:
    variants: +X
  hdf5:
    variants: +hl+szip+threadsafe
  libfabric:
    variants: fabrics=sockets,tcp,verbs,rxd,rxm
  mpich:
    variants: device=ch4 netmod=ofi
  pango:
    variants: +X
  pcre:
    variants: +jit
  vim:
    variants: features=huge +python
  all:
    # Keep in sync with install script
    compiler: [gcc@11.2.0]
    providers:
      mpi: [mpich]
    # Make sure to build for a generic architecture
    target: [x86_64_v3]
    # Warning: Adding global variants resets per-package variants (https://github.com/spack/spack/pull/10466)
