packages:
  adios:
    variants: +hdf5
  adios2:
    variants: +hdf5
  boost:
    # Valgrind depends on Boost with these variants
    variants: +atomic+chrono+date_time+exception+filesystem+graph+iostreams+locale+log+math+program_options+random+regex+serialization+signals+system+test+thread+timer+wave
  cairo:
    # FIXME +svg cannot be concretized at the moment
    variants: +fc+ft+gobject+pdf+png+X
  curl:
    variants: +libidn2
  doxygen:
    variants: +graphviz
  gdb:
    variants: ~python
  gdbm:
    # FIXME Work around concretizer bug:
    # https://github.com/spack/spack/issues/26585
    version: [1.19]
  gnuplot:
    variants: +X
  hdf5:
    variants: +hl+szip+threadsafe
  libfabric:
    variants: fabrics=sockets,tcp,udp,verbs,rxd,rxm
  libffi:
    # FIXME gobject-introspection currently requires 3.3, resulting in duplicated packages
    version: [3.3]
  libfuse:
    # FIXME Check whether this needs to be the same version as the system FUSE
    variants: ~utils
  mpich:
    variants: device=ch4 netmod=ofi
  pango:
    variants: +X
  pcre:
    variants: +jit
  py-numpy:
    # FIXME We currently end up with two versions of py-numpy
    version: [1.22.4]
  py-setuptools:
    # FIXME We currently end up with two versions of py-setuptools
    version: [59.4.0]
  vim:
    variants: features=huge +python
  zstd:
    variants: +programs
  all:
    # Keep in sync with install script
    compiler: [gcc@12.1.0]
    providers:
      mpi: [mpich]
    # Make sure to build for a generic architecture
    target: [x86_64_v3]
    # Warning: Adding global variants resets per-package variants (https://github.com/spack/spack/pull/10466)
