packages:
  adios:
    require: "+hdf5"
  adios2:
    require: "+hdf5"
  boost:
    # Valgrind depends on Boost with these variants
    require: "+atomic+chrono+exception+system+thread"
  cairo:
    # FIXME +svg cannot be concretized at the moment
    require: "+fc+ft+gobject+pdf+png+X"
  curl:
    require: "+libidn2"
  doxygen:
    require: "+graphviz"
  gdb:
    require: "~python"
  gnuplot:
    require: "+X"
  hdf5:
    require: "+hl+szip+threadsafe"
  libfabric:
    require: "fabrics=sockets,tcp,udp,verbs,rxd,rxm"
  libfuse:
    # FIXME Check whether this needs to be the same version as the system FUSE
    require: "~utils"
  libssh2:
    require: "crypto=mbedtls"
  mbedtls:
    require: "libs=shared,static"
  mpi:
    require: "mpich"
  mpich:
    require: "device=ch4 netmod=ofi"
  pango:
    require: "+X"
  pcre:
    require: "+jit"
  py-setuptools:
    # FIXME We currently end up with two versions of py-setuptools (and many dependents)
    version: [59.4.0]
  vim:
    require: "features=huge +python"
  zstd:
    require: "+programs"
  all:
    # FIXME We cannot use requirements here (https://github.com/spack/spack/issues/34341)
    # Keep in sync with install script
    compiler: [gcc@12.2.0]
    # Make sure to build for a generic architecture
    target: [x86_64_v3]
    # Warning: Adding global variants resets per-package variants (https://github.com/spack/spack/pull/10466)
